name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image name and tags
        run: |
          IMAGE_BASE="ghcr.io/${GITHUB_REPOSITORY,,}/ocr-service"
          DATE_TAG=$(date +'%Y%m%d%H%M%S')

          echo "IMAGE_BASE=$IMAGE_BASE" >> $GITHUB_ENV
          echo "DATE_TAG=$DATE_TAG" >> $GITHUB_ENV

      - name: Build Docker image with two tags
        run: |
          docker build -t ${{ env.IMAGE_BASE }}:latest -t ${{ env.IMAGE_BASE }}:${{ env.DATE_TAG }} .

      - name: Push Docker images
        run: |
          docker push ${{ env.IMAGE_BASE }}:latest
          docker push ${{ env.IMAGE_BASE }}:${{ env.DATE_TAG }}
